.TH MARKOV 1 2024-06-11

.SH NAME
markov \- Markov algorithms interpreter and collection

.SH SYNOPSIS
.B ./markov.sh
[\fB\-h\fP|\fB\--help\fP]
[\fB\-u\fP|\fB\--usage\fP]
[\fB\-rc\fP|\fB\--reset-config\fP]
.br
.B ./markov.sh
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
\fIalgorithm\-file\fP ...
.br
.B ./markov.sh
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
\fB\-s\fP|\fB\--sequence\fP
\fIsequence\-file\fP ...

.SH DESCRIPTION
.B markov.sh

.SH OPTIONS
.B markov.sh

.SH CONFIGURATION
.TP
The configuration allows each following option to be set or unset if not passed as an argument:
\fB\--no-colors\fP
.br
\fB\--verbose\fP
.br
\fB\--sequence\fP

.PP
Configuration is done by editing the configuration file.
.br
In line 4 of \fBmarkov.sh\fP the absolute path of the configuration file is set.
.br
In the unmodified \fBmarkov.sh\fP, this absolute path is \fB~/.config/markov/markov.conf\fP.

.TP
The configuration file is set automatically once \fBmarkov.sh\fP is launched, if any of these are true:
a) option \fB\-rc\fP|\fB\--reset-config\fP is passed
.br
b) the configuration file is empty
.br
c) the configuration file is not present
.br

.PP
In lines 9-11 of \fBmarkov.sh\fP, the data of the configuration file that is thus set can be modified.
.br
In the unmodified \fBmarkov.sh\fP, this data is \fBNO_COLORS=0; VERBOSE=0; SEQUENCE=0\fP.
.br
With such configuration file data, each corresponding option is unset if not passed as an argument.
.br
\fB1\fP written respectively in the configuration file will give the opposite result for an option.

.SH EXIT STATUS
.B markov

.SH RETURN VALUE
.B markov

.SH ERRORS
.B markov

.SH FILES
.B markov

.SH VERSIONS
.B markov

.SH NOTES
.B markov

.SH BUGS
.B markov

.SH EXAMPLES
.B markov

.SH AUTHOR
.B markov

.SH SEE ALSO
.B markov
