.TH MARKOV 1 2024-06-10

.SH NAME
markov \- Markov algorithms interpreter and collection

.SH SYNOPSIS
.B markov
[\fB\-h\fP|\fB\--help\fP]
[\fB\-u\fP|\fB\--usage\fP]
[\fB\-rc\fP|\fB\--reset-config\fP]
.br
.B markov
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
\fIalgorithm\-file\fP ...
.br
.B markov
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
\fB\-s\fP
\fIsequence\-file\fP ...
.br
.B markov
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
\fB\--sequence\fP
\fIsequence\-file\fP ...

.SH DESCRIPTION
.B markov

.SH OPTIONS
.B markov

.SH CONFIGURATION
Configuration is done by editing the configuration file.
.br
The default absolute path of the configuration file is \fB~/.config/markov/markov.conf\fP.
.br
The default absolute path of the configuration file is set in line 4 of \fBmarkov.sh\fP.
.br
The configuration file allows the following options to be set or unset by default:

.SH EXIT STATUS
.B markov

.SH RETURN VALUE
.B markov

.SH ERRORS
.B markov

.SH FILES
.B markov

.SH VERSIONS
.B markov

.SH NOTES
.B markov

.SH BUGS
.B markov

.SH EXAMPLES
.B markov

.SH AUTHOR
.B markov

.SH SEE ALSO
.B markov
