.TH MARKOV 1 2024-06-10



.SH NAME
markov \- Markov algorithms interpreter and their largest library



.SH SYNOPSIS
.B ./markov.sh
[\fB\-V\fP|\fB\--version\fP]
[\fB\-u\fP|\fB\--usage\fP]
[\fB\-?\fP|\fB\-h\fP|\fB\--help\fP]
[\fB\-rc\fP|\fB\--reset-config\fP]
.br
.B ./markov.sh
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
[\fB\-c\fP|\fB\--count\fP]
\fIalgorithm\-file\fP ...
.br
.B ./markov.sh
[\fB\-nc\fP|\fB\--no-colors\fP]
[\fB\-v\fP|\fB\--verbose\fP]
[\fB\-c\fP|\fB\--count\fP]
\fB\-s\fP|\fB\--sequence\fP
\fIalgorithm-sequence\-file\fP ...



.SH DESCRIPTION
.B markov.sh



.SH OPTIONS
.RE
\fB\-V\fP, \fB\--version\fP
.RS
Display the version message and exit immediately.

.RE
\fB\-u\fP, \fB\--usage\fP
.RS
Display a usage message and exit immediately.

.RE
\fB\-?\fP, \fB\-h\fP, \fB\--help\fP
.RS
Display a help message and exit immediately.

.RE
\fB\-nc\fP, \fB\--no-colors\fP
.RS
Disable color escape sequences and proceed.
.br
They are disabled whether or not this option is set, if any of these are true:
.RS
a) \fBmarkov\fP output is not directed into the terminal
.br
b) user \fBecho\fP can not process escape-sequences

.RE
.RE
\fB\-v\fP, \fB\--verbose\fP
.RS
Display local changes in the processed word after each substituion rule is applied.
.br
Consider this option to be unset if a lot of substitution rules are expected to be applied.
.br
To know whether to use this option, launch \fBmarkov\fP with \fB\-c\fP|\fB\--count\fP option in advance.

.RE
\fB\-c\fP, \fB\--count\fP
.RS
Display the number of applied substituion rules once the execution is complete.

.RE
\fB\-s\fP, \fB\--sequence\fP
.RS
Process each passed file as an algorithm sequence rather than an algorithm.


.SH CONFIGURATION
.RE
The configuration allows each following option to be set or unset if not passed as an argument:
.RS
\fB\--no-colors\fP
.br
\fB\--verbose\fP
.br
\fB\--sequence\fP

.RE
Configuration is done by editing the configuration file.
.br
In line 4 of \fBmarkov.sh\fP the absolute path of the configuration file is set.
.br
In the unmodified \fBmarkov.sh\fP, this absolute path is \fB~/.config/markov/markov.conf\fP.

The configuration file is set automatically once \fBmarkov.sh\fP is launched, if any of these are true:
.RS
a) option \fB\-rc\fP|\fB\--reset-config\fP is passed
.br
b) the configuration file is empty
.br
c) the configuration file is not present
.br

.RE
In lines 9-11 of \fBmarkov.sh\fP, the data of the configuration file that is thus set can be modified.
.br
In the unmodified \fBmarkov.sh\fP, this data is \fBNO_COLORS=0; VERBOSE=0; SEQUENCE=0\fP.
.br
With such configuration file data, each corresponding option is unset if not passed as an argument.
.br
\fB1\fP written respectively in the configuration file will give the opposite result for an option.



.SH FILES
.B markov



.SH ERRORS
.B markov



.SH EXIT STATUS
.B markov



.SH EXAMPLES
.B markov



.SH AUTHOR
.B markov



.SH SEE ALSO
.B markov
